<?php

/**
 * @file
 * Contains tattoo.module.
 *
 * @todo Add support for encoding default values of entity fields.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implement hook_page_attachments().
 *
 * @param array $page
 */
function tattoo_page_attachments(array &$page) {
  if ($domain = \Drupal::config('rest.settings')->get('link_domain')) {
    $linkDomain = rtrim($domain, '/');
  }
  else {
    $request = \Drupal::request();
    $linkDomain = $request->getSchemeAndHttpHost() . $request->getBasePath();
  }

  $page['#attached']['drupalSettings']['restLinkDomain'] = $linkDomain;
}

/**
 * Implements hook_entity_view().
 *
 * @param array $build
 * @param EntityInterface $entity
 * @param EntityViewDisplayInterface $display
 * @param $view_mode
 */
function tattoo_entity_view(
  array &$build,
  EntityInterface $entity,
  EntityViewDisplayInterface $display,
  $view_mode
) {
  $config = \Drupal::config('tattoo.settings')->get('entity_types.'. $entity->getEntityTypeId());

  if ($config && in_array($entity->bundle(), $config)) {
    /** @var \Drupal\tattoo\Parlor $parlor */
    $parlor = \Drupal::service('tattoo.parlor');

    $build['#attached']['html_head'][] = $parlor->toHead($entity);
  }
}
